// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PointOfSaleDataAccess;

#nullable disable

namespace PointOfSaleDataAccess.Migrations
{
    [DbContext(typeof(POSDBContext))]
    [Migration("20231218042558_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PointOfSaleSystem.Models.Invoice.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ComapnyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("OtherCost")
                        .HasColumnType("float");

                    b.Property<string>("StockBarcodePrefix")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("TotalItemCost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("StockBarcodePrefix")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("PointOfSaleSystem.Models.Products.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BarcodePrefix")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BarcodePrefix = "1001",
                            CreatedDate = new DateTime(2023, 12, 18, 9, 55, 57, 458, DateTimeKind.Local).AddTicks(1897),
                            Name = "Product 1",
                            UpdatedDate = new DateTime(2023, 12, 18, 9, 55, 57, 458, DateTimeKind.Local).AddTicks(1914)
                        },
                        new
                        {
                            Id = 2L,
                            BarcodePrefix = "1002",
                            CreatedDate = new DateTime(2023, 12, 18, 9, 55, 57, 458, DateTimeKind.Local).AddTicks(1916),
                            Name = "Product 2",
                            UpdatedDate = new DateTime(2023, 12, 18, 9, 55, 57, 458, DateTimeKind.Local).AddTicks(1917)
                        },
                        new
                        {
                            Id = 3L,
                            BarcodePrefix = "1003",
                            CreatedDate = new DateTime(2023, 12, 18, 9, 55, 57, 458, DateTimeKind.Local).AddTicks(1918),
                            Name = "Product 3",
                            UpdatedDate = new DateTime(2023, 12, 18, 9, 55, 57, 458, DateTimeKind.Local).AddTicks(1919)
                        },
                        new
                        {
                            Id = 4L,
                            BarcodePrefix = "1004",
                            CreatedDate = new DateTime(2023, 12, 18, 9, 55, 57, 458, DateTimeKind.Local).AddTicks(1920),
                            Name = "Product 4",
                            UpdatedDate = new DateTime(2023, 12, 18, 9, 55, 57, 458, DateTimeKind.Local).AddTicks(1921)
                        },
                        new
                        {
                            Id = 5L,
                            BarcodePrefix = "1005",
                            CreatedDate = new DateTime(2023, 12, 18, 9, 55, 57, 458, DateTimeKind.Local).AddTicks(1922),
                            Name = "Product 5",
                            UpdatedDate = new DateTime(2023, 12, 18, 9, 55, 57, 458, DateTimeKind.Local).AddTicks(1923)
                        });
                });

            modelBuilder.Entity("PointOfSaleSystem.Models.Stock.InvoiceStock", b =>
                {
                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<long>("StockId")
                        .HasColumnType("bigint");

                    b.HasKey("InvoiceId", "StockId");

                    b.ToTable("InvoiceStocks");
                });

            modelBuilder.Entity("PointOfSaleSystem.Models.Stock.Stock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<double>("UnitCost")
                        .HasColumnType("float");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActionType = 0,
                            CreatedDate = new DateTime(2023, 12, 18, 9, 55, 57, 458, DateTimeKind.Local).AddTicks(2066),
                            ProductId = 1L,
                            Quantity = 10,
                            Type = 0,
                            UnitCost = 123.34,
                            UnitPrice = 125.34
                        },
                        new
                        {
                            Id = 2L,
                            ActionType = 0,
                            CreatedDate = new DateTime(2023, 12, 18, 9, 55, 57, 458, DateTimeKind.Local).AddTicks(2069),
                            ProductId = 2L,
                            Quantity = 10,
                            Type = 0,
                            UnitCost = 12.09,
                            UnitPrice = 14.09
                        },
                        new
                        {
                            Id = 3L,
                            ActionType = 0,
                            CreatedDate = new DateTime(2023, 12, 18, 9, 55, 57, 458, DateTimeKind.Local).AddTicks(2071),
                            ProductId = 3L,
                            Quantity = 100,
                            Type = 0,
                            UnitCost = 2.0,
                            UnitPrice = 4.0
                        },
                        new
                        {
                            Id = 4L,
                            ActionType = 0,
                            CreatedDate = new DateTime(2023, 12, 18, 9, 55, 57, 458, DateTimeKind.Local).AddTicks(2073),
                            ProductId = 4L,
                            Quantity = 1000,
                            Type = 0,
                            UnitCost = 500.0,
                            UnitPrice = 600.0
                        },
                        new
                        {
                            Id = 5L,
                            ActionType = 0,
                            CreatedDate = new DateTime(2023, 12, 18, 9, 55, 57, 458, DateTimeKind.Local).AddTicks(2074),
                            ProductId = 5L,
                            Quantity = 5,
                            Type = 0,
                            UnitCost = 124.0,
                            UnitPrice = 126.0
                        },
                        new
                        {
                            Id = 6L,
                            ActionType = 0,
                            CreatedDate = new DateTime(2023, 12, 18, 9, 55, 57, 458, DateTimeKind.Local).AddTicks(2075),
                            ProductId = 1L,
                            Quantity = 35,
                            Type = 0,
                            UnitCost = 126.34,
                            UnitPrice = 128.34
                        });
                });

            modelBuilder.Entity("PointOfSaleSystem.Models.Stock.InvoiceStock", b =>
                {
                    b.HasOne("PointOfSaleSystem.Models.Invoice.Invoice", null)
                        .WithMany("InvoiceStocks")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PointOfSaleSystem.Models.Stock.Stock", b =>
                {
                    b.HasOne("PointOfSaleSystem.Models.Products.Product", "Item")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PointOfSaleSystem.Models.Invoice.Invoice", b =>
                {
                    b.Navigation("InvoiceStocks");
                });

            modelBuilder.Entity("PointOfSaleSystem.Models.Products.Product", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
