// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PointOfSaleDataAccess;

#nullable disable

namespace PointOfSaleDataAccess.Migrations
{
    [DbContext(typeof(POSDBContext))]
    [Migration("20231216034213_stockEntity")]
    partial class stockEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PointOfSaleSystem.Models.StockEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BarcodePrefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("UnitCost")
                        .HasColumnType("float");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BarcodePrefix = "X1",
                            CreatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2241),
                            ProductId = 1L,
                            Quantity = 10,
                            UnitCost = 123.34,
                            UnitPrice = 125.34,
                            UpdatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2242)
                        },
                        new
                        {
                            Id = 2L,
                            BarcodePrefix = "X2",
                            CreatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2245),
                            ProductId = 2L,
                            Quantity = 10,
                            UnitCost = 12.09,
                            UnitPrice = 14.09,
                            UpdatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2245)
                        },
                        new
                        {
                            Id = 3L,
                            BarcodePrefix = "X3",
                            CreatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2247),
                            ProductId = 3L,
                            Quantity = 100,
                            UnitCost = 2.0,
                            UnitPrice = 4.0,
                            UpdatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2248)
                        },
                        new
                        {
                            Id = 4L,
                            BarcodePrefix = "X4",
                            CreatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2249),
                            ProductId = 4L,
                            Quantity = 1000,
                            UnitCost = 500.0,
                            UnitPrice = 600.0,
                            UpdatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2250)
                        },
                        new
                        {
                            Id = 5L,
                            BarcodePrefix = "X5",
                            CreatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2251),
                            ProductId = 5L,
                            Quantity = 5,
                            UnitCost = 124.0,
                            UnitPrice = 126.0,
                            UpdatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2252)
                        },
                        new
                        {
                            Id = 6L,
                            BarcodePrefix = "X11",
                            CreatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2253),
                            ProductId = 1L,
                            Quantity = 35,
                            UnitCost = 126.34,
                            UnitPrice = 128.34,
                            UpdatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2254)
                        });
                });

            modelBuilder.Entity("PointOfSaleSystemAPI.Models.ProductEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BarcodePrefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BarcodePrefix = "1001",
                            CreatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2078),
                            Name = "Product 1",
                            UpdatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2088)
                        },
                        new
                        {
                            Id = 2L,
                            BarcodePrefix = "1002",
                            CreatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2090),
                            Name = "Product 2",
                            UpdatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2091)
                        },
                        new
                        {
                            Id = 3L,
                            BarcodePrefix = "1003",
                            CreatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2092),
                            Name = "Product 3",
                            UpdatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2093)
                        },
                        new
                        {
                            Id = 4L,
                            BarcodePrefix = "1004",
                            CreatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2094),
                            Name = "Product 4",
                            UpdatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2095)
                        },
                        new
                        {
                            Id = 5L,
                            BarcodePrefix = "1005",
                            CreatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2096),
                            Name = "Product 5",
                            UpdatedDate = new DateTime(2023, 12, 16, 9, 12, 13, 132, DateTimeKind.Local).AddTicks(2097)
                        });
                });

            modelBuilder.Entity("PointOfSaleSystem.Models.StockEntity", b =>
                {
                    b.HasOne("PointOfSaleSystemAPI.Models.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
